// <auto-generated />
using System;
using CoodeshTechChallenge.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoodeshTechChallenge.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoodeshTechChallenge.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CURSO DE BEM-ESTAR"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DOMINANDO INVESTIMENTOS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DESENVOLVEDOR FULL STACK"
                        });
                });

            modelBuilder.Entity("CoodeshTechChallenge.Domain.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "JOSE CARLOS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "MARIA CANDIDA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "THIAGO OLIVEIRA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ELIANA NOGUEIRA"
                        },
                        new
                        {
                            Id = 5,
                            Name = "CARLOS BATISTA"
                        },
                        new
                        {
                            Id = 6,
                            Name = "CAROLINA MACHADO"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CELSO DE MELO"
                        });
                });

            modelBuilder.Entity("CoodeshTechChallenge.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Product")
                        .HasColumnType("int");

                    b.Property<int>("Seller")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("CoodeshTechChallenge.Domain.Type", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Venda produtor"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Venda afiliado"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Comissão paga"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Comissão recebida"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
